export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: string;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      announcement_bar: {
        Row: {
          id: string;
          text: string;
          link_url: string | null;
          bg_color: string | null;
          text_color: string | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          text: string;
          link_url?: string | null;
          bg_color?: string | null;
          text_color?: string | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          text?: string;
          link_url?: string | null;
          bg_color?: string | null;
          text_color?: string | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bd_courier_settings: {
        Row: {
          id: string;
          is_enabled: boolean | null;
          api_key: string | null;
          base_url: string | null;
          cache_duration_days: number | null;
          auto_check_new_orders: boolean | null;
          max_retries: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          is_enabled?: boolean | null;
          api_key?: string | null;
          base_url?: string | null;
          cache_duration_days?: number | null;
          auto_check_new_orders?: boolean | null;
          max_retries?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          is_enabled?: boolean | null;
          api_key?: string | null;
          base_url?: string | null;
          cache_duration_days?: number | null;
          auto_check_new_orders?: boolean | null;
          max_retries?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          sort_order: number | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      collections: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          accent_color: string | null;
          is_featured: boolean | null;
          is_active: boolean | null;
          sort_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          accent_color?: string | null;
          is_featured?: boolean | null;
          is_active?: boolean | null;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          accent_color?: string | null;
          is_featured?: boolean | null;
          is_active?: boolean | null;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversion_events: {
        Row: {
          id: string;
          order_id: string;
          transaction_id: string;
          provider: string;
          event_name: string;
          event_id: string;
          status: string | null;
          payload: Json | null;
          error_message: string | null;
          sent_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          transaction_id: string;
          provider: string;
          event_name: string;
          event_id: string;
          status?: string | null;
          payload?: Json | null;
          error_message?: string | null;
          sent_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          transaction_id?: string;
          provider?: string;
          event_name?: string;
          event_id?: string;
          status?: string | null;
          payload?: Json | null;
          error_message?: string | null;
          sent_at?: string;
          created_at?: string;
        };
      };
      courier_api_logs: {
        Row: {
          id: string;
          phone: string;
          order_id: string | null;
          source: string;
          status: string;
          latency_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          phone: string;
          order_id?: string | null;
          source: string;
          status: string;
          latency_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          order_id?: string | null;
          source?: string;
          status?: string;
          latency_ms?: number | null;
          created_at?: string;
        };
      };
      courier_check_cache: {
        Row: {
          id: string;
          phone: string;
          status: string;
          summary_total_parcel: number | null;
          summary_success_parcel: number | null;
          summary_cancelled_parcel: number | null;
          summary_success_ratio: number | null;
          risk_level: string | null;
          couriers: Json | null;
          reports: Json | null;
          raw_response: Json | null;
          last_error: string | null;
          retry_count: number | null;
          checking_status: string | null;
          checking_started_at: string | null;
          checked_at: string;
          expires_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          phone: string;
          status?: string;
          summary_total_parcel?: number | null;
          summary_success_parcel?: number | null;
          summary_cancelled_parcel?: number | null;
          summary_success_ratio?: number | null;
          risk_level?: string | null;
          couriers?: Json | null;
          reports?: Json | null;
          raw_response?: Json | null;
          last_error?: string | null;
          retry_count?: number | null;
          checking_status?: string | null;
          checking_started_at?: string | null;
          checked_at?: string;
          expires_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          status?: string;
          summary_total_parcel?: number | null;
          summary_success_parcel?: number | null;
          summary_cancelled_parcel?: number | null;
          summary_success_ratio?: number | null;
          risk_level?: string | null;
          couriers?: Json | null;
          reports?: Json | null;
          raw_response?: Json | null;
          last_error?: string | null;
          retry_count?: number | null;
          checking_status?: string | null;
          checking_started_at?: string | null;
          checked_at?: string;
          expires_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      delivery_settings: {
        Row: {
          id: string;
          inside_dhaka_fee: number;
          outside_dhaka_fee: number;
          free_delivery_threshold: number | null;
          is_active: boolean | null;
          delivery_note: string | null;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          inside_dhaka_fee?: number;
          outside_dhaka_fee?: number;
          free_delivery_threshold?: number | null;
          is_active?: boolean | null;
          delivery_note?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          inside_dhaka_fee?: number;
          outside_dhaka_fee?: number;
          free_delivery_threshold?: number | null;
          is_active?: boolean | null;
          delivery_note?: string | null;
          updated_at?: string;
          created_at?: string;
        };
      };
      footer_groups: {
        Row: {
          id: string;
          title: string;
          links: Json | null;
          sort_order: number | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          links?: Json | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          links?: Json | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      hero_slides: {
        Row: {
          id: string;
          title: string;
          subtitle: string | null;
          badge: string | null;
          image_url: string;
          mobile_image_url: string | null;
          cta_text: string | null;
          cta_link: string | null;
          secondary_cta_text: string | null;
          secondary_cta_link: string | null;
          sort_order: number | null;
          is_active: boolean | null;
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          subtitle?: string | null;
          badge?: string | null;
          image_url: string;
          mobile_image_url?: string | null;
          cta_text?: string | null;
          cta_link?: string | null;
          secondary_cta_text?: string | null;
          secondary_cta_link?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          subtitle?: string | null;
          badge?: string | null;
          image_url?: string;
          mobile_image_url?: string | null;
          cta_text?: string | null;
          cta_link?: string | null;
          secondary_cta_text?: string | null;
          secondary_cta_link?: string | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      homepage_sections: {
        Row: {
          id: string;
          section_key: string;
          title: string;
          subtitle: string | null;
          is_enabled: boolean | null;
          sort_order: number | null;
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          section_key: string;
          title: string;
          subtitle?: string | null;
          is_enabled?: boolean | null;
          sort_order?: number | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          section_key?: string;
          title?: string;
          subtitle?: string | null;
          is_enabled?: boolean | null;
          sort_order?: number | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      navigation_items: {
        Row: {
          id: string;
          label: string;
          url: string;
          is_external: boolean | null;
          sort_order: number | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          label: string;
          url: string;
          is_external?: boolean | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          url?: string;
          is_external?: boolean | null;
          sort_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      newsletter_subscribers: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          status: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          status?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          status?: string | null;
          created_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string | null;
          product_id: string | null;
          product_name: string;
          product_image: string | null;
          color_name: string | null;
          size: string | null;
          quantity: number;
          unit_price: number;
          subtotal: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          product_id?: string | null;
          product_name: string;
          product_image?: string | null;
          color_name?: string | null;
          size?: string | null;
          quantity: number;
          unit_price: number;
          subtotal: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          product_id?: string | null;
          product_name?: string;
          product_image?: string | null;
          color_name?: string | null;
          size?: string | null;
          quantity?: number;
          unit_price?: number;
          subtotal?: number;
          created_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_name: string;
          phone: string;
          email: string | null;
          address: string;
          city: string | null;
          area: string | null;
          postal_code: string | null;
          notes: string | null;
          payment_method: string | null;
          subtotal: number;
          delivery_charge: number;
          discount: number | null;
          total: number;
          status: string | null;
          created_at: string;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_term: string | null;
          utm_content: string | null;
          gclid: string | null;
          fbclid: string | null;
          ttclid: string | null;
          courier_provider: string | null;
          courier_consignment_id: string | null;
          courier_tracking_code: string | null;
          courier_status: string | null;
          courier_sent_at: string | null;
          courier_response: Json | null;
          courier_check_id: string | null;
          courier_success_ratio: number | null;
          courier_risk_level: string | null;
          courier_total_parcels: number | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          order_number: string;
          customer_name: string;
          phone: string;
          email?: string | null;
          address: string;
          city?: string | null;
          area?: string | null;
          postal_code?: string | null;
          notes?: string | null;
          payment_method?: string | null;
          subtotal: number;
          delivery_charge: number;
          discount?: number | null;
          total: number;
          status?: string | null;
          created_at?: string;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          gclid?: string | null;
          fbclid?: string | null;
          ttclid?: string | null;
          courier_provider?: string | null;
          courier_consignment_id?: string | null;
          courier_tracking_code?: string | null;
          courier_status?: string | null;
          courier_sent_at?: string | null;
          courier_response?: Json | null;
          courier_check_id?: string | null;
          courier_success_ratio?: number | null;
          courier_risk_level?: string | null;
          courier_total_parcels?: number | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          order_number?: string;
          customer_name?: string;
          phone?: string;
          email?: string | null;
          address?: string;
          city?: string | null;
          area?: string | null;
          postal_code?: string | null;
          notes?: string | null;
          payment_method?: string | null;
          subtotal?: number;
          delivery_charge?: number;
          discount?: number | null;
          total?: number;
          status?: string | null;
          created_at?: string;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          gclid?: string | null;
          fbclid?: string | null;
          ttclid?: string | null;
          courier_provider?: string | null;
          courier_consignment_id?: string | null;
          courier_tracking_code?: string | null;
          courier_status?: string | null;
          courier_sent_at?: string | null;
          courier_response?: Json | null;
          courier_check_id?: string | null;
          courier_success_ratio?: number | null;
          courier_risk_level?: string | null;
          courier_total_parcels?: number | null;
          updated_at?: string | null;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          subtitle: string | null;
          description: string | null;
          price: number;
          compare_price: number | null;
          badge: string | null;
          category_name: string | null;
          rating: number | null;
          reviews_count: number | null;
          image_url: string;
          gallery: Json | null;
          colors: Json | null;
          sizes: Json | null;
          is_featured: boolean | null;
          is_new: boolean | null;
          stock: number | null;
          created_at: string;
          slug: string | null;
          sku: string | null;
          status: string | null;
          cost_price: number | null;
          low_stock_threshold: number | null;
          card_settings: Json | null;
          seo_title: string | null;
          seo_description: string | null;
          sort_order: number | null;
          category_id: string | null;
          collection_id: string | null;
          fabric_details: string | null;
          care_instructions: string | null;
          is_active: boolean | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          name: string;
          subtitle?: string | null;
          description?: string | null;
          price: number;
          compare_price?: number | null;
          badge?: string | null;
          category_name?: string | null;
          rating?: number | null;
          reviews_count?: number | null;
          image_url: string;
          gallery?: Json | null;
          colors?: Json | null;
          sizes?: Json | null;
          is_featured?: boolean | null;
          is_new?: boolean | null;
          stock?: number | null;
          created_at?: string;
          slug?: string | null;
          sku?: string | null;
          status?: string | null;
          cost_price?: number | null;
          low_stock_threshold?: number | null;
          card_settings?: Json | null;
          seo_title?: string | null;
          seo_description?: string | null;
          sort_order?: number | null;
          category_id?: string | null;
          collection_id?: string | null;
          fabric_details?: string | null;
          care_instructions?: string | null;
          is_active?: boolean | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          subtitle?: string | null;
          description?: string | null;
          price?: number;
          compare_price?: number | null;
          badge?: string | null;
          category_name?: string | null;
          rating?: number | null;
          reviews_count?: number | null;
          image_url?: string;
          gallery?: Json | null;
          colors?: Json | null;
          sizes?: Json | null;
          is_featured?: boolean | null;
          is_new?: boolean | null;
          stock?: number | null;
          created_at?: string;
          slug?: string | null;
          sku?: string | null;
          status?: string | null;
          cost_price?: number | null;
          low_stock_threshold?: number | null;
          card_settings?: Json | null;
          seo_title?: string | null;
          seo_description?: string | null;
          sort_order?: number | null;
          category_id?: string | null;
          collection_id?: string | null;
          fabric_details?: string | null;
          care_instructions?: string | null;
          is_active?: boolean | null;
          updated_at?: string | null;
        };
      };
      site_settings: {
        Row: {
          id: string;
          store_name: string | null;
          tagline: string | null;
          logo_url: string | null;
          favicon_url: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          facebook_url: string | null;
          instagram_url: string | null;
          whatsapp_number: string | null;
          currency: string | null;
          currency_symbol: string | null;
          brand_story: string | null;
          custom_css: string | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image: string | null;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          store_name?: string | null;
          tagline?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          facebook_url?: string | null;
          instagram_url?: string | null;
          whatsapp_number?: string | null;
          currency?: string | null;
          currency_symbol?: string | null;
          brand_story?: string | null;
          custom_css?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          store_name?: string | null;
          tagline?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          facebook_url?: string | null;
          instagram_url?: string | null;
          whatsapp_number?: string | null;
          currency?: string | null;
          currency_symbol?: string | null;
          brand_story?: string | null;
          custom_css?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image?: string | null;
          updated_at?: string;
          created_at?: string;
        };
      };
      steadfast_settings: {
        Row: {
          id: string;
          is_enabled: boolean | null;
          api_key: string | null;
          secret_key: string | null;
          base_url: string | null;
          default_delivery_type: number | null;
          default_note: string | null;
          auto_send_on_confirm: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          is_enabled?: boolean | null;
          api_key?: string | null;
          secret_key?: string | null;
          base_url?: string | null;
          default_delivery_type?: number | null;
          default_note?: string | null;
          auto_send_on_confirm?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          is_enabled?: boolean | null;
          api_key?: string | null;
          secret_key?: string | null;
          base_url?: string | null;
          default_delivery_type?: number | null;
          default_note?: string | null;
          auto_send_on_confirm?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      testimonials: {
        Row: {
          id: string;
          customer_name: string;
          city: string | null;
          avatar_url: string | null;
          review: string;
          rating: number | null;
          is_featured: boolean | null;
          is_active: boolean | null;
          sort_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          customer_name: string;
          city?: string | null;
          avatar_url?: string | null;
          review: string;
          rating?: number | null;
          is_featured?: boolean | null;
          is_active?: boolean | null;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          city?: string | null;
          avatar_url?: string | null;
          review?: string;
          rating?: number | null;
          is_featured?: boolean | null;
          is_active?: boolean | null;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tracking_events_config: {
        Row: {
          id: string;
          name: string;
          category: string | null;
          enabled: boolean | null;
          ga4_enabled: boolean | null;
          google_ads_enabled: boolean | null;
          meta_enabled: boolean | null;
          tiktok_enabled: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          category?: string | null;
          enabled?: boolean | null;
          ga4_enabled?: boolean | null;
          google_ads_enabled?: boolean | null;
          meta_enabled?: boolean | null;
          tiktok_enabled?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string | null;
          enabled?: boolean | null;
          ga4_enabled?: boolean | null;
          google_ads_enabled?: boolean | null;
          meta_enabled?: boolean | null;
          tiktok_enabled?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tracking_settings: {
        Row: {
          id: string;
          gtm_enabled: boolean | null;
          gtm_container_id: string | null;
          ga4_enabled: boolean | null;
          ga4_measurement_id: string | null;
          google_ads_enabled: boolean | null;
          google_ads_conversion_id: string | null;
          google_ads_purchase_label: string | null;
          google_ads_cart_label: string | null;
          google_ads_begin_checkout_label: string | null;
          meta_enabled: boolean | null;
          meta_pixel_id: string | null;
          meta_capi_enabled: boolean | null;
          tiktok_enabled: boolean | null;
          tiktok_pixel_id: string | null;
          tiktok_events_api_enabled: boolean | null;
          advanced_matching_enabled: boolean | null;
          debug_mode: boolean | null;
          consent_mode_enabled: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gtm_enabled?: boolean | null;
          gtm_container_id?: string | null;
          ga4_enabled?: boolean | null;
          ga4_measurement_id?: string | null;
          google_ads_enabled?: boolean | null;
          google_ads_conversion_id?: string | null;
          google_ads_purchase_label?: string | null;
          google_ads_cart_label?: string | null;
          google_ads_begin_checkout_label?: string | null;
          meta_enabled?: boolean | null;
          meta_pixel_id?: string | null;
          meta_capi_enabled?: boolean | null;
          tiktok_enabled?: boolean | null;
          tiktok_pixel_id?: string | null;
          tiktok_events_api_enabled?: boolean | null;
          advanced_matching_enabled?: boolean | null;
          debug_mode?: boolean | null;
          consent_mode_enabled?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          gtm_enabled?: boolean | null;
          gtm_container_id?: string | null;
          ga4_enabled?: boolean | null;
          ga4_measurement_id?: string | null;
          google_ads_enabled?: boolean | null;
          google_ads_conversion_id?: string | null;
          google_ads_purchase_label?: string | null;
          google_ads_cart_label?: string | null;
          google_ads_begin_checkout_label?: string | null;
          meta_enabled?: boolean | null;
          meta_pixel_id?: string | null;
          meta_capi_enabled?: boolean | null;
          tiktok_enabled?: boolean | null;
          tiktok_pixel_id?: string | null;
          tiktok_events_api_enabled?: boolean | null;
          advanced_matching_enabled?: boolean | null;
          debug_mode?: boolean | null;
          consent_mode_enabled?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
